services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_NAME: "b2broker-test"
      DB_HOST: postgres
  postgres:
    image: postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      PGDATA: /data/postgres
      POSTGRES_DB: "b2broker-test"
      POSTGRES_PASSWORD: postgres
