name: local

services:
  redis:
    image: "redis:alpine"
  db:
    image: postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      PGDATA: /data/postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"

volumes:
  db:
