# Generated by Django 5.1.7 on 2025-03-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['id']},
        ),
    ]
