# Generated by Django 5.1.7 on 2025-03-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_transaction_options_alter_wallet_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='txid',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
