# Generated by Django 5.1.7 on 2025-03-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_transaction_txid_alter_wallet_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='label',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
